### PR TITLE
DM-32440: update the User Guide

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by wvreeven — CHANGES_REQUESTED** [review]
This is a nice addition. However, as you pointed out yourself on Slack, it would be great to have an example for how to monitor the connection to the OneClientServer in a simple client. Can you please add one?

**Review by wvreeven — APPROVED** [review]
Thanks for the useful addition.

**Comment by r-owen** [comment]
I added an example of read monitoring for a client application. I also took another cleanup pass to make the read monitor examples more consistent with the read example and echo server example.

**Review by wvreeven — APPROVED** [review]
LGTM

**Pull request merged**
